-- MySQL
INSERT INTO `pet_data_produto`.`tb_produto`
(`nome`, `descricao`, `categoria`, `valor`,`quantidade`) VALUES
('Ração Nova Carne', 'Ração para animais nobre e bonitinhos', 'Alimentação',1.99, 15),
('Ração Carne de Cabra', 'Ração para animais nobre e fofos', 'Alimentação',2.42, 17),
('Ração Carne de Peixe', 'Ração para animais feios e magros', 'Alimentação',3.53, 12),
('Ração Carne de Treco', 'Ração para animais que não comem nenhum trem', 'Alimentação',4.00, 32),
('Remédio 01', 'Remédio para seu animal!', 'Farmácia',5.90, 16),
('Remédio 02', 'Remédio para seu animal!', 'Farmácia',10.93, 32),
('Remédio 03', 'Remédio para seu animal!', 'Farmácia',99.99, 12),
('Remédio 04', 'Remédio para seu animal!', 'Farmácia',21.00, 42),
('Remédio 05', 'Remédio para seu animal!', 'Farmácia',92.42, 22),
('Remédio 06', 'Remédio para seu animal!', 'Farmácia',34.21, 35),
('Remédio 07', 'Remédio para seu animal!', 'Farmácia',41.23, 56),
('Roupinha Colorida 03', 'Roupas novas pro seu cão não andar mais pelado por aí!', 'Roupas',2.33, 86),
('Roupinha Colorida 02', 'Roupas novas pro seu cão não andar mais pelado por aí!', 'Roupas',5.21, 56),
('Roupinha Colorida 01', 'Roupas novas pro seu cão não andar mais pelado por aí!', 'Roupas',64.32, 56),
('Roupinha Colorida 04', 'Roupas novas pro seu cão não andar mais pelado por aí!', 'Roupas',32.12, 77),
('Roupinha Colorida 05', 'Roupas novas pro seu cão não andar mais pelado por aí!', 'Roupas',1.23, 55),
('Roupinha Colorida 06', 'Roupas novas pro seu cão não andar mais pelado por aí!', 'Roupas',5.21, 44),
('Roupinha Colorida 08', 'Roupas novas pro seu cão não andar mais pelado por aí!', 'Roupas',3.65, 34),
('Roupinha Colorida 23', 'Roupas novas pro seu cão não andar mais pelado por aí!', 'Roupas',47.88, 43),
('Roupinha Colorida 21', 'Roupas novas pro seu cão não andar mais pelado por aí!', 'Roupas',56.44, 21),
('Roupinha Colorida 25', 'Roupas novas pro seu cão não andar mais pelado por aí!', 'Roupas',34.54, 32),
('Roupinha Colorida 35', 'Roupas novas pro seu cão não andar mais pelado por aí!', 'Roupas',1.44, 12),
('Roupinha Colorida 43', 'Roupas novas pro seu cão não andar mais pelado por aí!', 'Roupas',2.77, 11),
('Brinquedo 01', 'Brinquedo bacana pra esse bicho animal', 'Toys',75.32, 2),
('Brinquedo 02', 'Brinquedo bacana pra esse bicho animal', 'Toys',144.02, 3),
('Brinquedo 03', 'Brinquedo bacana pra esse bicho animal', 'Toys',123.21, 5),
('Brinquedo 04', 'Brinquedo bacana pra esse bicho animal', 'Toys',23.42, 1),
('Brinquedo 05', 'Brinquedo bacana pra esse bicho animal', 'Toys',42.22, 6),
('Brinquedo 06', 'Brinquedo bacana pra esse bicho animal', 'Toys',46.74, 7),
('Brinquedo 07', 'Brinquedo bacana pra esse bicho animal', 'Toys',57.45, 54),
('Brinquedo 08', 'Brinquedo bacana pra esse bicho animal', 'Toys',75.65, 55),
('Brinquedo 09', 'Brinquedo bacana pra esse bicho animal', 'Toys',45.45, 23);